const incoming = [
    {
        template: "attenx",
        tempname: "Attend Call",
        name: "Alex",
        nf: "30",
        nc: "#ffffff",
        nfor: "Roboto-Black",
        time: "1:00PM",
        tc: "#ffffff",
        tf: "18",
        tfor: "Roboto-Black",
        profile: "",
        screen: 'Attencall1',
        action: '',
        actionValue: 'temp1',
        scenename: "",
        chromaicon: '',
        chromacolor: '',
        bg: false
    },
    {
        template: "atteny",
        tempname: "Attend call ",
        name: "Linda",
        nf: "30",
        nc: "#ffffff",
        nfor: "Roboto-Black",
        time: "12:00 AM",
        tc: "#ffffff",
        tf: "18",
        tfor: "Roboto-Black",
        profile: "",
        screen: 'Attencall2',
        action: '',
        actionValue: 'temp2',
        scenename: "",
        chromaicon: '',
        chromacolor: '',
        bg: false
    },
    {
        template: "gallery",
        tempname: "Gallery",
        name: "Linda",
        nf: "30",
        nc: "#ffffff",
        nfor: "Roboto-Black",
        time: "12:00 AM",
        tc: "#ffffff",
        tf: "18",
        tfor: "Roboto-Black",
        profile: "",
        screen: 'gallery',
        action: '',
        actionValue: 'temp2',
        scenename: "",
        chromaicon: '',
        chromacolor: '',
        bg:false
    },
    {
        template: "outgoing",
        tempname: "Out Going Call",
        name: "Alex",
        nf: "30",
        nc: "#ffffff",
        nfor: "Roboto-Black",
        time: "1:00PM",
        tc: "#ffffff",
        tf: "18",
        tfor: "Roboto-Black",
        scenename: '',
        profile: "",
        screen: 'outgoing',
        action: '',
        actionValue: '',
        chromaicon: '',
        chromacolor: '',
        bg: false
    },
    {
        template: "iphonex",
        tempname: "Incoming Call",
        name: "Alex",
        nf: "30",
        nc: "#ffffff",
        nfor: "Roboto-Black",
        time: "1:00PM",
        tc: "#ffffff",
        tf: "18",
        tfor: "Roboto-Black",
        scenename: '',
        profile: "",
        screen: 'IncomingCall1',
        action: '',
        actionValue: '',
        chromaicon: '',
        chromacolor: '',
        bg: false
    },
    {
        template: "chroma",
        tempname: "Chroma Key",
        name: "Alex",
        nf: "30",
        nc: "#ffffff",
        nfor: "Roboto-Black",
        time: "1:00PM",
        tc: "#ffffff",
        tf: "18",
        tfor: "Roboto-Black",
        scenename: '',
        profile: "",
        screen: 'chroma',
        action: '',
        actionValue: '',
        chromaicon: '',
        chromacolor: '',
        bg: false
    },
    {
        template: "message",
        tempname: "Message",
        name: "Alex",
        nf: "30",
        nc: "#ffffff",
        nfor: "Roboto-Black",
        time: "1:00PM",
        tc: "#ffffff",
        tf: "18",
        tfor: "Roboto-Black",
        scenename: '',
        profile: "",
        screen: 'message',
        action: '',
        actionValue: '',
        chromaicon: '',
        chromacolor: '',
        bg: false
    }
]
export default incoming;